-- Access codes for pre–April 7 gate: only owner devices or users with a valid code can access the site.
-- Architect generates codes in Settings; users enter phone + code on the landing to get access.

CREATE TABLE IF NOT EXISTS public.access_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  phone_number TEXT NOT NULL,
  code TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by_phone TEXT,
  CONSTRAINT access_codes_phone_code_unique UNIQUE (phone_number, code)
);

CREATE INDEX IF NOT EXISTS idx_access_codes_phone ON public.access_codes(phone_number);
CREATE INDEX IF NOT EXISTS idx_access_codes_created_at ON public.access_codes(created_at);

COMMENT ON TABLE public.access_codes IS 'Codes generated by architect for users to access the site until April 7. One code per phone.';

-- RPC: Validate phone + code. Returns ok + phone if valid.
CREATE OR REPLACE FUNCTION public.validate_access_code(
  p_phone_number TEXT,
  p_code TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_phone TEXT;
BEGIN
  IF NULLIF(TRIM(COALESCE(p_phone_number, '')), '') IS NULL
     OR NULLIF(TRIM(COALESCE(p_code, '')), '') IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'phone_number and code required');
  END IF;

  SELECT ac.phone_number INTO v_phone
  FROM public.access_codes ac
  WHERE ac.phone_number = TRIM(p_phone_number)
    AND ac.code = TRIM(p_code)
  LIMIT 1;

  IF v_phone IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Invalid code or phone number');
  END IF;

  RETURN jsonb_build_object('ok', true, 'phone_number', v_phone);
END;
$$;

COMMENT ON FUNCTION public.validate_access_code(TEXT, TEXT) IS 'Validate access code for a phone; used by landing until April 7.';

-- RPC: Generate a code for a phone (architect only; caller must enforce). Returns the code.
CREATE OR REPLACE FUNCTION public.generate_access_code(
  p_phone_number TEXT,
  p_created_by_phone TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_code TEXT;
  v_exists BOOLEAN;
BEGIN
  IF NULLIF(TRIM(COALESCE(p_phone_number, '')), '') IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'phone_number required');
  END IF;

  -- 6-digit numeric code
  v_code := lpad(floor(random() * 1000000)::text, 6, '0');

  -- If this phone already has a code, update it; else insert
  SELECT EXISTS(SELECT 1 FROM public.access_codes WHERE phone_number = TRIM(p_phone_number)) INTO v_exists;
  IF v_exists THEN
    UPDATE public.access_codes
    SET code = v_code, created_at = now(), created_by_phone = NULLIF(TRIM(COALESCE(p_created_by_phone, '')), '')
    WHERE phone_number = TRIM(p_phone_number);
  ELSE
    INSERT INTO public.access_codes (phone_number, code, created_by_phone)
    VALUES (TRIM(p_phone_number), v_code, NULLIF(TRIM(COALESCE(p_created_by_phone, '')), ''));
  END IF;

  RETURN jsonb_build_object('ok', true, 'code', v_code, 'phone_number', TRIM(p_phone_number));
END;
$$;

COMMENT ON FUNCTION public.generate_access_code(TEXT, TEXT) IS 'Generate a 6-digit access code for a phone. Call from Settings (architect only).';

GRANT EXECUTE ON FUNCTION public.validate_access_code(TEXT, TEXT) TO anon;
GRANT EXECUTE ON FUNCTION public.validate_access_code(TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_access_code(TEXT, TEXT) TO anon;
GRANT EXECUTE ON FUNCTION public.generate_access_code(TEXT, TEXT) TO authenticated;
